### PR TITLE
Make Lookbook compatible with Ruby 2.5

### PR DESCRIPTION
**Pull request by DRBragg**
At work we're currently running a fork of Lookbook so it works on Ruby 2.5. As it turns out the necessary changes are actually pretty minimal and I'd love to just be able to point to the real gem. Hence this PR.

It's 100% cool if you dont want to merge this.  I dont mind maintaining the fork until we're on 2.6 but I thought it was better to open the PR and close it then not even try.

I'm happy walk through any or all of this with you but the main changes are:
- Use `Array#select` and `Hash#select` over `#filter` (`#filter` is an alias to `#select` anyway)
- Ensure `base_path` is a `Pathname` in `Page`.  In Ruby <= 2.5 a string wont implicitly convert to a pathname which causes issues when trying to use the pages feature for us. Creating a `Pathname` by default fixes this. I know pages is an experimental feature so totally cool if you dont want to merge this part. We dont have to use pages.

Let me know what you think. Thanks!

### CODE REVIEW

**Comment by allmarkedup** [comment]
@DRBragg this is fantastic, thank you! I'm absolutely up for getting Lookbook running on older versions of Ruby wherever possible. My only real constraint is time (and Ruby knowledge!) so PRs like this are super helpful.

The only issue with this PR as far as I can see is the bumping of the Lookbook version number - that is something that I will need to handle as part of the release process. Would you be able to remove that commit from the PR? I'll give it a quick test to double check there are no issues but otherwise I'll get this merged in once that change is made.

Thanks again for this 👍

**Comment by DRBragg** [comment]
> @DRBragg this is fantastic, thank you! I'm absolutely up for getting Lookbook running on older versions of Ruby wherever possible. My only real constraint is time (and Ruby knowledge!) so PRs like this are super helpful.
> 
> The only issue with this PR as far as I can see is the bumping of the Lookbook version number - that is something that I will need to handle as part of the release process. Would you be able to remove that commit from the PR? I'll give it a quick test to double check there are no issues but otherwise I'll get this merged in once that change is made.
> 
> Thanks again for this 👍
> 

Sure thing! I'll revert that as soon as I get back in front of a computer. Thanks for taking a look!

**Comment by allmarkedup** [comment]
Nice one, thanks @DRBragg - I've just given this a test and it all seems good so I'll merge it in now and get a new release out. Really appreciate your contribution.

I've actually just released [an early beta of what will become Lookbook v1.0](https://github.com/allmarkedup/lookbook/issues/96) - I will also make sure that these changes get merged into that branch soon, and I'll go through the codebase to try to make sure no new non-2.5 compatible changes have crept in. I'll let you know when I think it's ready in case you want to give it a test at some point :-)

**Comment by DRBragg** [comment]
> Nice one, thanks @DRBragg - I've just given this a test and it all seems good so I'll merge it in now and get a new release out. Really appreciate your contribution.
> 
> I've actually just released [an early beta of what will become Lookbook v1.0](https://github.com/allmarkedup/lookbook/issues/96) - I will also make sure that these changes get merged into that branch soon, and I'll go through the codebase to try to make sure no new non-2.5 compatible changes have crept in. I'll let you know when I think it's ready in case you want to give it a test at some point :-)
> 

Awesome! Definitely happy to test

**Pull request merged**
